// AUTO-GENERATED by scripts/build-static-data.ts — do not edit by hand.
import type { Property } from "@/lib/types";

export const PROPERTIES: Property[] = [
  {
    "id": "marina-vista-residences",
    "name": "Marina Vista Residences",
    "developer": "Azure Bay Developments",
    "area": "Dubai Marina",
    "status": "UNDER_REVIEW",
    "bedrooms": "1BR",
    "sizeSqft": 750,
    "handoverQuarter": "Q4 2027",
    "listPrice": 1912500,
    "pricePerSqft": 2550,
    "downPaymentPct": 20,
    "serviceChargePerSqft": 18,
    "expectedRentAnnual": 130000,
    "dldFeePct": 4,
    "documents": [
      {
        "id": "marina-vista-brochure",
        "type": "BROCHURE",
        "title": "Marina Vista Residences — Investor Brochure",
        "fileUrl": "/documents/marina-vista-residences/marina-vista-brochure.pdf",
        "pageCount": 6
      },
      {
        "id": "marina-vista-spa",
        "type": "SPA",
        "title": "Marina Vista Residences — Sale and Purchase Agreement",
        "fileUrl": "/documents/marina-vista-residences/marina-vista-spa.pdf",
        "pageCount": 6
      },
      {
        "id": "marina-vista-payment-plan",
        "type": "PAYMENT_PLAN",
        "title": "Marina Vista Residences — Payment Plan",
        "fileUrl": "/documents/marina-vista-residences/marina-vista-payment-plan.pdf",
        "pageCount": 5
      },
      {
        "id": "marina-vista-market-report",
        "type": "MARKET_REPORT",
        "title": "Dubai Marina Submarket Report — H1 2026",
        "fileUrl": "/documents/marina-vista-residences/marina-vista-market-report.pdf",
        "pageCount": 5
      }
    ],
    "chatThreads": [
      {
        "type": "GENERAL",
        "messages": [
          {
            "id": "marina-vista-residences-general-0",
            "role": "USER",
            "content": "Can you give me a quick rundown on Marina Vista Residences and who's building it?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-general-1",
            "role": "ASSISTANT",
            "content": "Marina Vista Residences is a 42-storey, 318-unit waterfront tower in Dubai Marina developed by Azure Bay Developments, with the 1BR collection you're looking at on floors 9-30. Azure Bay has delivered four towers in the Marina/JBR area since 2014 totalling roughly 1,650 units, with three of four projects handed over within four months of schedule — their most recent tower, Azure Bay Tower 3, was about seven weeks late in 2024. Construction on Marina Vista started Q1 2025 and the brochure cites ~22% progress as of Q2 2026, targeting Q4 2027 handover.",
            "citations": [
              {
                "documentId": "marina-vista-brochure",
                "page": 1,
                "snippet": "Marina Vista Residences is a 42-storey waterfront tower rising on the last remaining plot along the Dubai Marina promenade"
              },
              {
                "documentId": "marina-vista-brochure",
                "page": 4,
                "snippet": "on-time delivery record of three out of four projects handed over within four months"
              }
            ]
          },
          {
            "id": "marina-vista-residences-general-2",
            "role": "USER",
            "content": "Is this unit a good size compared to other 1BRs in the building?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-general-3",
            "role": "ASSISTANT",
            "content": "Your unit, Type 1B-04, is 750 sqft including a 68 sqft balcony, which sits right in the middle of the building's 1BR range of 720-810 sqft — so it's a fairly standard mid-size layout, not the smallest or largest option. It has floor-to-ceiling windows, one covered parking bay, and a storage locker on the same floor, with ceiling heights of 2.95m versus the Marina norm of roughly 2.7m for comparable towers. If marina views matter to you, note that odd-numbered floors above level 15 are specifically oriented to avoid the neighboring tower's service wing.",
            "citations": [
              {
                "documentId": "marina-vista-brochure",
                "page": 2,
                "snippet": "The 1BR units in Marina Vista Residences range from 720 to 810 sqft"
              }
            ]
          }
        ]
      },
      {
        "type": "FINANCIAL",
        "messages": [
          {
            "id": "marina-vista-residences-financial-0",
            "role": "USER",
            "content": "What does the actual payment schedule look like, and does it match what I'd expect for a Marina launch?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-financial-1",
            "role": "ASSISTANT",
            "content": "It's a 90/10 construction-linked plan: 20% across booking and signing, seven milestone-linked instalments of 10% each from 20% to 90% construction completion, and a final 10% on handover — so nothing above 20% is due until the unit is actually built out. That's a lighter post-handover burden than several current Marina launches that have shifted toward heavier post-handover weighting, per the payment plan overview. At AED 1,912,500, each 10% milestone instalment works out to AED 191,250.",
            "citations": [
              {
                "documentId": "marina-vista-payment-plan",
                "page": 1,
                "snippet": "This structure carries a lower post-handover exposure than many current Dubai Marina launches"
              },
              {
                "documentId": "marina-vista-payment-plan",
                "page": 2,
                "snippet": "Installment 4 — 35% Construction Complete — 10% — AED 191,250"
              }
            ]
          },
          {
            "id": "marina-vista-residences-financial-2",
            "role": "USER",
            "content": "How does the yield actually pencil out once you factor in service charges?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-financial-3",
            "role": "ASSISTANT",
            "content": "Using the AED 130,000 expected annual rent against the AED 18/sqft service charge on 750 sqft (AED 13,500/year), net operating income is about AED 116,500. Against the all-in acquisition cost of AED 1,912,500 plus 4% DLD fee (AED 1,989,000 total), that's a net yield of roughly 5.9% before financing costs — which lines up well with the market report's estimate of 5.3-6.1% net yields for comparable Marina 1BRs after service charges.",
            "citations": [
              {
                "documentId": "marina-vista-market-report",
                "page": 2,
                "snippet": "net yields for well-let 1BR units in the Marina typically fall in the range of 5.3% to 6.1%"
              }
            ]
          }
        ]
      },
      {
        "type": "LEGAL",
        "messages": [
          {
            "id": "marina-vista-residences-legal-0",
            "role": "USER",
            "content": "What happens if I miss a payment — how much could I actually lose?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-legal-1",
            "role": "ASSISTANT",
            "content": "Under Clause 14.1, missing an instalment by 30 days triggers a default notice with a 15-day cure period. If you don't cure within that window, Clause 14.2 lets the Developer terminate and retain 25% of the Purchase Price — AED 478,125 on your unit — as liquidated damages, refunding the rest only after the unit is resold. That 25% forfeiture is on the higher side of what's typical, though it's meaningfully better than some competing projects that forfeit up to 40%, so it's worth building payment reminders into your calendar given the cure period is short.",
            "citations": [
              {
                "documentId": "marina-vista-spa",
                "page": 5,
                "snippet": "the Developer shall be entitled to retain 25% of the Purchase Price as agreed liquidated damages"
              }
            ]
          },
          {
            "id": "marina-vista-residences-legal-2",
            "role": "USER",
            "content": "The brochure says AED 18/sqft for service charges — is that locked in by the SPA?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-legal-3",
            "role": "ASSISTANT",
            "content": "No — Clause 11.2 explicitly says AED 18/sqft is only an initial estimate, and the Developer reserves the right to make 'reasonable adjustments' before the Owners Association is even formed, without needing your consent. That's flagged in our audit as a medium-risk item because 'reasonable' is undefined and there's no cap, though it's less severe than fully uncapped escalation clauses we've seen elsewhere since disputes over the approved budget can eventually be referred to the Rental Dispute Settlement Centre under Clause 11.3.",
            "citations": [
              {
                "documentId": "marina-vista-spa",
                "page": 4,
                "snippet": "the Developer reserves the right to make reasonable adjustments to this estimate prior to formation of the Owners Association"
              }
            ]
          }
        ]
      },
      {
        "type": "LOCATION",
        "messages": [
          {
            "id": "marina-vista-residences-location-0",
            "role": "USER",
            "content": "How walkable is this to the metro and tram, realistically?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-location-1",
            "role": "ASSISTANT",
            "content": "Quite walkable — the Dubai Tram's Marina Towers stop is about 220 metres from the main entrance, and the DMCC Metro Station on the Red Line is roughly a six-minute walk, so you've got both tram and metro interchange within easy reach. Marina Mall is about 350 metres away, and Marina Walk's dining and retail strip is within a 10-minute walk as well.",
            "citations": [
              {
                "documentId": "marina-vista-brochure",
                "page": 5,
                "snippet": "The Dubai Tram's Marina Towers stop is closer still, roughly 220 metres from the building's main entrance"
              }
            ]
          },
          {
            "id": "marina-vista-residences-location-2",
            "role": "USER",
            "content": "Is this priced reasonably against other Marina towers nearby?",
            "citations": []
          },
          {
            "id": "marina-vista-residences-location-3",
            "role": "ASSISTANT",
            "content": "It's in line with the comp set. At AED 2,550/sqft, Marina Vista is about 3% above Waterside Residences' secondary-market price of AED 2,390/sqft, but close to Marina Quay Tower's most recent off-plan pricing of AED 2,480/sqft, and below completed Marina Bay Heights resales at AED 2,610/sqft. Service charges across all three comparables run AED 15.50-19.80/sqft, so the AED 18/sqft estimate here is squarely within range rather than an outlier.",
            "citations": [
              {
                "documentId": "marina-vista-market-report",
                "page": 3,
                "snippet": "Marina Vista Residences' launch price of AED 2,550 per sqft sits within this comparable range"
              }
            ]
          }
        ]
      }
    ],
    "auditFindings": [
      {
        "id": "marina-vista-residences-audit-0",
        "documentId": "marina-vista-spa",
        "clauseRef": "Clause 11.2",
        "title": "Unilateral service charge adjustment before Owners Association formation",
        "quote": "the Developer reserves the right to make reasonable adjustments to this estimate prior to formation of the Owners Association to reflect actual operating costs of shared facilities, and such adjustment shall not require the Purchaser's consent",
        "page": 4,
        "severity": "MEDIUM",
        "explanation": "The AED 18/sqft figure quoted throughout the marketing materials is only an estimate the Developer can revise unilaterally before the Owners Association exists to push back, and 'reasonable' is not defined by reference to any index or ceiling. This creates uncertainty in yield calculations that rely on the quoted service charge.",
        "recommendation": "Ask the Developer to cap any pre-formation adjustment at a fixed percentage (e.g. no more than 10% above the quoted estimate) or tie it to a published cost index."
      },
      {
        "id": "marina-vista-residences-audit-1",
        "documentId": "marina-vista-spa",
        "clauseRef": "Clause 14.2",
        "title": "25% forfeiture on default with short cure period",
        "quote": "the Developer may terminate this Agreement by written notice, in which case the Developer shall be entitled to retain 25% of the Purchase Price as agreed liquidated damages",
        "page": 5,
        "severity": "MEDIUM",
        "explanation": "A 15-day cure period combined with a flat 25% forfeiture is a significant penalty for what could be a single missed instalment, and the refund of the balance is only due after resale of the unit, with no fixed timeline given for that resale to occur.",
        "recommendation": "Negotiate a longer cure period (30 days) and a fixed maximum timeframe (e.g. 120 days) for refunding the balance after termination, regardless of whether resale has completed."
      },
      {
        "id": "marina-vista-residences-audit-2",
        "documentId": "marina-vista-spa",
        "clauseRef": "Clause 9.1",
        "title": "12-month grace period with no compensation for delay",
        "quote": "subject to a grace period of twelve (12) months from the Anticipated Completion Date (the \"Grace Period\") during which no compensation, penalty, or right of termination shall accrue to the Purchaser on account of delay",
        "page": 3,
        "severity": "MEDIUM",
        "explanation": "A full 12-month grace period is longer than the 6-month period seen in some other Dubai off-plan SPAs, meaning the Purchaser has no contractual remedy for delay for up to three years after signing (handover date plus grace period) without any compensation accruing.",
        "recommendation": "Push to shorten the grace period to 6 months, or negotiate a per-month compensation mechanism (e.g. a rent-equivalent credit) for delays beyond the Anticipated Completion Date."
      },
      {
        "id": "marina-vista-residences-audit-3",
        "documentId": "marina-vista-spa",
        "clauseRef": "Clause 17.1",
        "title": "Resale restricted until 40% paid, plus NOC fee",
        "quote": "The Purchaser may not assign, sell, or otherwise transfer its rights under this Agreement prior to payment of 40% of the Purchase Price without the prior written consent of the Developer",
        "page": 6,
        "severity": "LOW",
        "explanation": "This limits the Purchaser's exit flexibility during the first several construction-linked instalments, and any permitted assignment still carries an NOC fee of AED 5,250 or 0.5% of the Purchase Price. This is a fairly standard restriction in Dubai off-plan contracts, but investors planning to flip pre-handover should be aware of the 40% threshold.",
        "recommendation": "If early resale is part of your strategy, confirm the exact percentage paid at each milestone against the 40% threshold before committing, and budget for the NOC fee in your exit math."
      }
    ],
    "extractionFields": [
      {
        "key": "unitNumber",
        "label": "Unit Number",
        "value": "1B-04-17",
        "confidence": 0.97,
        "page": 1
      },
      {
        "key": "unitType",
        "label": "Unit Type",
        "value": "1 Bedroom",
        "confidence": 0.98,
        "page": 2
      },
      {
        "key": "sizeSqft",
        "label": "Size (sqft)",
        "value": "750",
        "confidence": 0.96,
        "page": 2
      },
      {
        "key": "listPrice",
        "label": "List Price (AED)",
        "value": "1,912,500",
        "confidence": 0.99,
        "page": 2
      },
      {
        "key": "pricePerSqft",
        "label": "Price per sqft (AED)",
        "value": "2,550",
        "confidence": 0.93,
        "page": 1
      },
      {
        "key": "downPaymentPct",
        "label": "Down Payment (%)",
        "value": "20",
        "confidence": 0.95,
        "page": 1
      },
      {
        "key": "handoverQuarter",
        "label": "Handover Quarter",
        "value": "Q4 2027",
        "confidence": 0.9,
        "page": 3
      },
      {
        "key": "serviceChargePerSqft",
        "label": "Service Charge (AED/sqft/yr)",
        "value": "18",
        "confidence": 0.7,
        "page": 4
      },
      {
        "key": "developer",
        "label": "Developer",
        "value": "Azure Bay Developments",
        "confidence": 0.99,
        "page": 1
      },
      {
        "key": "area",
        "label": "Area",
        "value": "Dubai Marina",
        "confidence": 0.99,
        "page": 1
      },
      {
        "key": "dldFeePct",
        "label": "DLD Transfer Fee (%)",
        "value": "4",
        "confidence": 0.96,
        "page": 5
      },
      {
        "key": "constructionProgress",
        "label": "Construction Progress (as of Q2 2026)",
        "value": "~22%",
        "confidence": 0.62,
        "page": 3
      }
    ]
  },
  {
    "id": "creek-horizon-tower",
    "name": "Creek Horizon Tower",
    "developer": "Vantage Point Developments",
    "area": "Dubai Creek Harbour",
    "status": "TRACKING",
    "bedrooms": "Studio",
    "sizeSqft": 420,
    "handoverQuarter": "Q2 2029",
    "listPrice": 840000,
    "pricePerSqft": 2000,
    "downPaymentPct": 10,
    "serviceChargePerSqft": 16,
    "expectedRentAnnual": 60000,
    "dldFeePct": 4,
    "documents": [
      {
        "id": "creek-horizon-brochure",
        "type": "BROCHURE",
        "title": "Creek Horizon Tower — Investor Brochure",
        "fileUrl": "/documents/creek-horizon-tower/creek-horizon-brochure.pdf",
        "pageCount": 6
      },
      {
        "id": "creek-horizon-spa",
        "type": "SPA",
        "title": "Creek Horizon Tower — Sale and Purchase Agreement",
        "fileUrl": "/documents/creek-horizon-tower/creek-horizon-spa.pdf",
        "pageCount": 8
      },
      {
        "id": "creek-horizon-payment-plan",
        "type": "PAYMENT_PLAN",
        "title": "Creek Horizon Tower — Payment Plan",
        "fileUrl": "/documents/creek-horizon-tower/creek-horizon-payment-plan.pdf",
        "pageCount": 6
      },
      {
        "id": "creek-horizon-market-report",
        "type": "MARKET_REPORT",
        "title": "Dubai Creek Harbour Submarket Report — H1 2026",
        "fileUrl": "/documents/creek-horizon-tower/creek-horizon-market-report.pdf",
        "pageCount": 5
      }
    ],
    "chatThreads": [
      {
        "type": "GENERAL",
        "messages": [
          {
            "id": "creek-horizon-tower-general-0",
            "role": "USER",
            "content": "What's the story with Creek Horizon Tower and Vantage Point Developments — are they established?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-general-1",
            "role": "ASSISTANT",
            "content": "Vantage Point Developments is a relatively young developer with only two completed projects, both in Business Bay since 2018, totalling about 640 units — and both were delivered late, by nine months and four months respectively. Creek Horizon Tower is their first project in Dubai Creek Harbour and their largest by unit count (512 units), currently at the piling stage with construction starting Q3 2025. Given that track record and the fact this is their first project in a new district for them, I'd treat the Q2 2029 handover target as fairly soft.",
            "citations": [
              {
                "documentId": "creek-horizon-brochure",
                "page": 4,
                "snippet": "Its first project was delivered nine months behind its original schedule; its second was delivered approximately four months behind schedule"
              }
            ]
          },
          {
            "id": "creek-horizon-tower-general-2",
            "role": "USER",
            "content": "What exactly do you get in the studio unit?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-general-3",
            "role": "ASSISTANT",
            "content": "Unit ST-06-11 is 420 sqft including a 40 sqft balcony — a combined living/sleeping area, a kitchenette along one wall, and one bathroom. Worth flagging: full-size appliances like a washing machine are a paid upgrade, not standard, and covered parking costs an extra AED 25,000 on top of the Purchase Price since the standard allocation is an uncovered bay. Amenity-wise it's fairly bare-bones for the district — no cinema room or private dining like some larger Creek Harbour towers offer.",
            "citations": [
              {
                "documentId": "creek-horizon-brochure",
                "page": 2,
                "snippet": "covered parking is available only as a paid upgrade of AED 25,000, payable separately from the Purchase Price"
              }
            ]
          }
        ]
      },
      {
        "type": "FINANCIAL",
        "messages": [
          {
            "id": "creek-horizon-tower-financial-0",
            "role": "USER",
            "content": "Walk me through this payment plan — it looks unusually back-loaded.",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-financial-1",
            "role": "ASSISTANT",
            "content": "It is — only 10% is due before and at signing (AED 84,000), 40% is spread across five construction milestones, and the remaining 50% (AED 420,000) is deferred into ten quarterly instalments of 5% each stretching 27 months after handover. That means you'll still owe 45% of the price the moment you get the keys, and those post-handover instalments keep coming whether or not the unit is tenanted, per Clause 4.3 of the SPA.",
            "citations": [
              {
                "documentId": "creek-horizon-payment-plan",
                "page": 1,
                "snippet": "half of the total Purchase Price remains outstanding after keys are handed over"
              },
              {
                "documentId": "creek-horizon-spa",
                "page": 2,
                "snippet": "Instalments due after Practical Completion shall continue in accordance with Schedule 2 regardless of whether the Purchaser has taken physical possession, obtained a tenant"
              }
            ]
          },
          {
            "id": "creek-horizon-tower-financial-2",
            "role": "USER",
            "content": "Does the yield still work if I assume some vacancy in there?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-financial-3",
            "role": "ASSISTANT",
            "content": "Base case: AED 60,000 rent minus AED 16/sqft x 420 sqft (AED 6,720) service charge gives AED 53,280 net operating income, against the AED 873,600 all-in cost (price plus 4% DLD), for a net yield of about 6.1% — near the top of the market report's 6.0-6.9% studio range. But the market report also flags that Creek Harbour service charges have risen 15-30% in year two post-handover for several towers as Owners Associations take over budgeting, and Clause 11.2 here has no cap at all, so that 6.1% could compress meaningfully if charges climb the way they have elsewhere in the district.",
            "citations": [
              {
                "documentId": "creek-horizon-market-report",
                "page": 2,
                "snippet": "several completed towers in the district have seen service charge increases of 15-30% in their second year of operation"
              },
              {
                "documentId": "creek-horizon-spa",
                "page": 4,
                "snippet": "no maximum annual increase or cap of any kind shall apply to such adjustments"
              }
            ]
          }
        ]
      },
      {
        "type": "LEGAL",
        "messages": [
          {
            "id": "creek-horizon-tower-legal-0",
            "role": "USER",
            "content": "This one worries me legally. What's the worst-case if I default on a payment?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-legal-1",
            "role": "ASSISTANT",
            "content": "It's genuinely one of the harsher default clauses I've seen in this set. Clause 14.1 gives you only a 10-day cure period after a default notice (versus 15-30 days elsewhere), and if you don't cure, Clause 14.2 lets the Developer keep up to 40% of the Purchase Price — AED 336,000 on your unit — as liquidated damages. Clause 14.4 also has you waive your right to argue that amount is disproportionate to their actual loss, and Clause 14.3 says if termination happens after Practical Completion, they can keep the full 40% even if you've paid less than that in total.",
            "citations": [
              {
                "documentId": "creek-horizon-spa",
                "page": 5,
                "snippet": "the Developer shall be entitled to retain up to 40% of the Purchase Price as agreed liquidated damages"
              }
            ]
          },
          {
            "id": "creek-horizon-tower-legal-2",
            "role": "USER",
            "content": "What about delays — how protected am I if construction drags on?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-legal-3",
            "role": "ASSISTANT",
            "content": "Not very. Clause 9.1 gives a 24-month grace period with zero compensation, and Clause 9.2 extends that further, without limit, for anything the Developer classifies as a 'Developer Delay Event' — which explicitly includes delays caused by the Developer's own contractors and subcontractors. On top of that, Clause 16.1's force majeure definition is extremely broad, covering things like contractor insolvency and adverse weather, and Clause 16.3 confirms no compensation is ever payable for force majeure delays while you keep paying instalments throughout. Combined, there's effectively no contractual mechanism that compensates you for a slow build.",
            "citations": [
              {
                "documentId": "creek-horizon-spa",
                "page": 3,
                "snippet": "The Grace Period shall be further extended, without limit, by any period during which a Developer Delay Event has occurred"
              },
              {
                "documentId": "creek-horizon-spa",
                "page": 6,
                "snippet": "No compensation, discount, rebate, or other remedy shall be payable or available to the Purchaser in respect of any delay"
              }
            ]
          },
          {
            "id": "creek-horizon-tower-legal-4",
            "role": "USER",
            "content": "Can they change the unit or finishes from what's shown in the brochure?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-legal-5",
            "role": "ASSISTANT",
            "content": "Yes, quite broadly. Clause 12.1 lets the Developer substitute materials, finishes, and fixtures at its sole discretion with no price adjustment, as long as it considers them 'comparable or better quality' — a standard they alone judge. Clause 12.2 also permits layout or boundary changes of up to 5% of the unit's area before you're entitled to any price reduction, and Clause 12.3 states the brochure and marketing materials aren't contractually binding at all. If exact specifications matter to you, this SPA gives you very little recourse if the delivered unit differs from what was marketed.",
            "citations": [
              {
                "documentId": "creek-horizon-spa",
                "page": 7,
                "snippet": "the Developer reserves the right, at its sole discretion, to substitute materials, finishes, brands, or fixtures with alternatives of comparable or better quality, without the Purchaser's consent"
              }
            ]
          }
        ]
      },
      {
        "type": "LOCATION",
        "messages": [
          {
            "id": "creek-horizon-tower-location-0",
            "role": "USER",
            "content": "How reliant is this project on future infrastructure that isn't built yet?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-location-1",
            "role": "ASSISTANT",
            "content": "Fairly reliant. The nearest planned metro connection is the Creek Harbour extension of the Green Line, still under construction with an expected 2027 opening — ahead of your Q2 2029 handover, but not guaranteed. More significantly, the signature Creek Tower project remains under review with no confirmed restart date, and a planned water taxi service connecting the Island District to Downtown is still only at proposal stage. None of these are contractual commitments, so I'd value the location on what exists today (Central Park and the boardwalk, partially open) rather than what's promised.",
            "citations": [
              {
                "documentId": "creek-horizon-market-report",
                "page": 4,
                "snippet": "the Creek Tower project, positioned as a signature landmark for the district, remains under review by the master developer as of Q2 2026, with no confirmed construction restart date"
              }
            ]
          },
          {
            "id": "creek-horizon-tower-location-2",
            "role": "USER",
            "content": "How does the price compare to similar studios launching nearby?",
            "citations": []
          },
          {
            "id": "creek-horizon-tower-location-3",
            "role": "ASSISTANT",
            "content": "At AED 2,000/sqft, Creek Horizon sits between Harbour Point Residences (AED 2,050/sqft at its 2025 launch) and Island Vista Tower (AED 1,890/sqft at its 2024 launch, now reselling around AED 2,100/sqft). The catch is that Creek Horizon is also the least advanced of the three — piling only, versus structural works underway at both comparables — and has the latest handover date of the group, so you're paying a similar price for a longer wait and more schedule risk.",
            "citations": [
              {
                "documentId": "creek-horizon-market-report",
                "page": 3,
                "snippet": "Creek Horizon Tower's launch price of AED 2,000 per sqft sits between these two comparables, and its Q2 2029 handover date is later than both"
              }
            ]
          }
        ]
      }
    ],
    "auditFindings": [
      {
        "id": "creek-horizon-tower-audit-0",
        "documentId": "creek-horizon-spa",
        "clauseRef": "Clause 11.2",
        "title": "Uncapped service charge escalation",
        "quote": "no maximum annual increase or cap of any kind shall apply to such adjustments",
        "page": 4,
        "severity": "HIGH",
        "explanation": "There is no ceiling on how much the Developer can raise the estimated service charge before the Owners Association forms, and Clause 11.3 makes the Developer's determination 'final and binding' until then. This directly undermines any yield calculation based on the quoted AED 16/sqft figure.",
        "recommendation": "Push for a hard cap (e.g. increases limited to a published inflation or cost index) or a maximum percentage increase per year until the Owners Association takes over budgeting."
      },
      {
        "id": "creek-horizon-tower-audit-1",
        "documentId": "creek-horizon-spa",
        "clauseRef": "Clause 14.2",
        "title": "Up to 40% forfeiture on default, with waiver of proportionality challenge",
        "quote": "the Developer shall be entitled to retain up to 40% of the Purchase Price as agreed liquidated damages",
        "page": 5,
        "severity": "HIGH",
        "explanation": "A 40% forfeiture rate is at the aggressive end of what's seen in Dubai off-plan contracts, and combined with only a 10-day cure period (Clause 14.1) and a waiver of the right to argue the penalty is disproportionate (Clause 14.4), a single missed post-handover instalment years into the plan could be catastrophic.",
        "recommendation": "Negotiate a graduated forfeiture scale tied to how much has been paid, a longer cure period (30 days), and removal of the proportionality waiver in Clause 14.4."
      },
      {
        "id": "creek-horizon-tower-audit-2",
        "documentId": "creek-horizon-spa",
        "clauseRef": "Clause 16.1 / 16.3",
        "title": "Overbroad force majeure definition with no purchaser compensation",
        "quote": "No compensation, discount, rebate, or other remedy shall be payable or available to the Purchaser in respect of any delay, cost increase, or other consequence arising from a Force Majeure Event",
        "page": 6,
        "severity": "HIGH",
        "explanation": "The force majeure definition sweeps in ordinary commercial risks like contractor insolvency and material shortages, which are arguably within the Developer's control to manage, not truly external events. Combined with the 24-month grace period, this leaves the Purchaser with almost no delay remedy for years while instalments continue.",
        "recommendation": "Narrow the force majeure definition to genuinely external events, and require the Developer to at minimum suspend post-handover-style instalment collection during any claimed force majeure period."
      },
      {
        "id": "creek-horizon-tower-audit-3",
        "documentId": "creek-horizon-spa",
        "clauseRef": "Clause 12.1",
        "title": "Unilateral right to substitute specifications and materials",
        "quote": "the Developer reserves the right, at its sole discretion, to substitute materials, finishes, brands, or fixtures with alternatives of comparable or better quality, without the Purchaser's consent and without any adjustment to the Purchase Price",
        "page": 7,
        "severity": "MEDIUM",
        "explanation": "The Developer alone decides what counts as 'comparable or better quality,' and Clause 12.3 confirms brochure and marketing materials are not contractual, so a Purchaser has very limited recourse if delivered finishes differ materially from what was marketed.",
        "recommendation": "Request that Schedule 3 finishes be incorporated as binding contractual specifications, with any substitution requiring purchaser sign-off for material changes."
      },
      {
        "id": "creek-horizon-tower-audit-4",
        "documentId": "creek-horizon-spa",
        "clauseRef": "Clause 17.2",
        "title": "High 2% assignment fee plus discretionary NOC refusal",
        "quote": "Any permitted assignment shall be subject to payment of an administrative and No Objection Certificate (NOC) fee equal to 2% of the Purchase Price",
        "page": 8,
        "severity": "MEDIUM",
        "explanation": "A 2% fee (AED 16,800 on this unit) is markedly higher than the flat or 0.5%-style fees seen on comparable projects, and Clause 17.3 lets the Developer refuse an NOC entirely below the 50%-paid threshold at its sole discretion, with no processing-time commitment under Clause 17.4.",
        "recommendation": "Negotiate the fee down toward a flat administrative charge or 0.5% of Purchase Price, and request a defined NOC processing timeframe (e.g. 15 business days)."
      },
      {
        "id": "creek-horizon-tower-audit-5",
        "documentId": "creek-horizon-spa",
        "clauseRef": "Clause 9.1 / 9.2",
        "title": "24-month grace period with unlimited further extension",
        "quote": "The Grace Period shall be further extended, without limit, by any period during which a Developer Delay Event has occurred, which for the purposes of this Agreement includes delays attributable to the Developer's contractors, subcontractors, or consultants",
        "page": 3,
        "severity": "HIGH",
        "explanation": "A 24-month grace period is already double what's seen in the Marina Vista Residences SPA, and the further unlimited extension for 'Developer Delay Events' — defined to include the Developer's own contractors — means the Purchaser has essentially no fixed outer date by which they can claim a remedy for delay.",
        "recommendation": "Cap the total extension (grace period plus Developer Delay Events) at a fixed outer limit, e.g. 36 months, beyond which termination rights or compensation apply automatically."
      }
    ],
    "extractionFields": [
      {
        "key": "unitNumber",
        "label": "Unit Number",
        "value": "ST-06-11",
        "confidence": 0.96,
        "page": 1
      },
      {
        "key": "unitType",
        "label": "Unit Type",
        "value": "Studio",
        "confidence": 0.98,
        "page": 2
      },
      {
        "key": "sizeSqft",
        "label": "Size (sqft)",
        "value": "420",
        "confidence": 0.95,
        "page": 2
      },
      {
        "key": "listPrice",
        "label": "List Price (AED)",
        "value": "840,000",
        "confidence": 0.99,
        "page": 2
      },
      {
        "key": "pricePerSqft",
        "label": "Price per sqft (AED)",
        "value": "2,000",
        "confidence": 0.92,
        "page": 1
      },
      {
        "key": "downPaymentPct",
        "label": "Down Payment (%)",
        "value": "10",
        "confidence": 0.94,
        "page": 1
      },
      {
        "key": "postHandoverPct",
        "label": "Post-Handover Balance (%)",
        "value": "50",
        "confidence": 0.93,
        "page": 1
      },
      {
        "key": "handoverQuarter",
        "label": "Handover Quarter",
        "value": "Q2 2029",
        "confidence": 0.85,
        "page": 3
      },
      {
        "key": "serviceChargePerSqft",
        "label": "Service Charge (AED/sqft/yr)",
        "value": "16",
        "confidence": 0.58,
        "page": 4
      },
      {
        "key": "developer",
        "label": "Developer",
        "value": "Vantage Point Developments",
        "confidence": 0.99,
        "page": 1
      },
      {
        "key": "area",
        "label": "Area",
        "value": "Dubai Creek Harbour",
        "confidence": 0.99,
        "page": 1
      },
      {
        "key": "constructionProgress",
        "label": "Construction Progress (as of Q2 2026)",
        "value": "~14%",
        "confidence": 0.6,
        "page": 3
      }
    ]
  }
];
