// AUTO-GENERATED by scripts/build-static-data.ts — do not edit by hand.
import type { DocumentType } from "@/lib/types";

export type WizardTemplateDoc = { fileUrl: string; pageCount: number; title: string; type: DocumentType };

export const WIZARD_TEMPLATE_DOCS: Record<string, WizardTemplateDoc> = {
  "sapphire-bay": {
    "fileUrl": "/documents/wizard-templates/sapphire-bay.pdf",
    "pageCount": 3,
    "title": "Sapphire Bay Residences Brochure",
    "type": "BROCHURE"
  },
  "meydan-horizon": {
    "fileUrl": "/documents/wizard-templates/meydan-horizon.pdf",
    "pageCount": 3,
    "title": "Meydan Horizon Villas Payment Plan",
    "type": "PAYMENT_PLAN"
  }
};
