import { writeFile } from "fs/promises";
import path from "path";
import * as XLSX from "xlsx";
import type { CatalogListing } from "@/lib/types";

// Adjust these aliases once you see the real column headers — matching is
// case-insensitive and ignores surrounding whitespace.
const COLUMN_ALIASES: Record<keyof Omit<CatalogListing, "id">, string[]> = {
  name: ["project name", "property name", "name", "project"],
  developer: ["developer", "developer name"],
  area: ["area", "location", "community"],
  bedrooms: ["bedrooms", "unit type", "configuration", "config", "beds"],
  sizeSqft: ["size (sqft)", "size sqft", "size", "area (sqft)", "unit size"],
  handoverQuarter: ["handover", "handover date", "completion", "completion date"],
  listPrice: ["price", "list price", "total price", "starting price", "price (aed)"],
  pricePerSqft: ["price per sqft", "price/sqft", "rate per sqft", "aed per sqft"],
  downPaymentPct: ["down payment", "down payment %", "down payment (%)"],
  serviceChargePerSqft: ["service charge", "service charge per sqft", "service charge (aed/sqft)"],
  expectedRentAnnual: ["expected rent", "annual rent", "expected annual rent", "rent (aed/yr)"],
  dldFeePct: ["dld fee", "dld %", "dld fee (%)"],
};

function normalizeHeader(h: string): string {
  return h.trim().toLowerCase();
}

function findColumn(headers: string[], aliases: string[]): string | undefined {
  const normalized = headers.map(normalizeHeader);
  for (const alias of aliases) {
    const idx = normalized.indexOf(alias);
    if (idx !== -1) return headers[idx];
  }
  return undefined;
}

function parseNumber(value: unknown): number | null {
  if (value === null || value === undefined || value === "") return null;
  if (typeof value === "number") return value;
  const cleaned = String(value).replace(/[^0-9.-]/g, "");
  const num = parseFloat(cleaned);
  return Number.isFinite(num) ? num : null;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

async function main() {
  const filePath = process.argv[2];
  if (!filePath) {
    console.error("Usage: tsx scripts/parse-offplan-excel.ts <path-to-excel-file> [sheet-name]");
    process.exit(1);
  }
  const sheetName = process.argv[3];

  const workbook = XLSX.readFile(filePath);
  const sheet = workbook.Sheets[sheetName ?? workbook.SheetNames[0]];
  if (!sheet) {
    console.error(`Sheet not found. Available sheets: ${workbook.SheetNames.join(", ")}`);
    process.exit(1);
  }

  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: null });
  if (rows.length === 0) {
    console.error("No rows found in sheet.");
    process.exit(1);
  }

  const headers = Object.keys(rows[0]);
  const columnMap = Object.fromEntries(
    Object.entries(COLUMN_ALIASES).map(([field, aliases]) => [field, findColumn(headers, aliases)])
  ) as Record<keyof Omit<CatalogListing, "id">, string | undefined>;

  const missing = Object.entries(columnMap).filter(([, col]) => !col);
  if (missing.length > 0) {
    console.warn(`Could not find a matching column for: ${missing.map(([f]) => f).join(", ")}`);
    console.warn(`Available headers: ${headers.join(", ")}`);
    console.warn("Update COLUMN_ALIASES in this script and re-run.\n");
  }

  const usedIds = new Set<string>();
  const listings: CatalogListing[] = rows.map((row) => {
    const name = columnMap.name ? String(row[columnMap.name] ?? "Untitled Project") : "Untitled Project";
    let id = slugify(name);
    while (usedIds.has(id)) id = `${id}-2`;
    usedIds.add(id);

    return {
      id,
      name,
      developer: columnMap.developer ? String(row[columnMap.developer] ?? "") : "",
      area: columnMap.area ? String(row[columnMap.area] ?? "") : "",
      bedrooms: columnMap.bedrooms ? String(row[columnMap.bedrooms] ?? "") || null : null,
      sizeSqft: columnMap.sizeSqft ? parseNumber(row[columnMap.sizeSqft]) : null,
      handoverQuarter: columnMap.handoverQuarter ? String(row[columnMap.handoverQuarter] ?? "") || null : null,
      listPrice: (columnMap.listPrice ? parseNumber(row[columnMap.listPrice]) : null) ?? 0,
      pricePerSqft: columnMap.pricePerSqft ? parseNumber(row[columnMap.pricePerSqft]) : null,
      downPaymentPct: columnMap.downPaymentPct ? parseNumber(row[columnMap.downPaymentPct]) : null,
      serviceChargePerSqft: columnMap.serviceChargePerSqft ? parseNumber(row[columnMap.serviceChargePerSqft]) : null,
      expectedRentAnnual: columnMap.expectedRentAnnual ? parseNumber(row[columnMap.expectedRentAnnual]) : null,
      dldFeePct: (columnMap.dldFeePct ? parseNumber(row[columnMap.dldFeePct]) : null) ?? 4,
    };
  });

  const outPath = path.join(process.cwd(), "lib", "data", "offplan-catalog.ts");
  const fileContents = `// AUTO-GENERATED by scripts/parse-offplan-excel.ts from "${path.basename(filePath)}" — do not edit by hand.\nimport type { CatalogListing } from "@/lib/types";\n\nexport const OFFPLAN_CATALOG: CatalogListing[] = ${JSON.stringify(listings, null, 2)};\n`;
  await writeFile(outPath, fileContents);

  console.log(`Parsed ${listings.length} listings from ${filePath}`);
  console.log(`Wrote lib/data/offplan-catalog.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
